version: '3'
services:
  leetcode-gateway-service:
    container_name: leetcode-gateway-service
    build: # 服务的 Docker 构建文件位置
      context: ./leetcode-gateway-service
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    networks:
      - mynetwork

  leetcode-user-service:
    container_name: leetcode-user-service
    build:
      context: ./leetcode-user-service
      dockerfile: Dockerfile
    ports:
      - "8102:8102"
    networks:
      - mynetwork
    depends_on: # 本服务依赖的服务，控制启动先后顺序
      - leetcode-gateway-service

  leetcode-question-service:
    container_name: leetcode-question-service
    build:
      context: ./leetcode-question-service
      dockerfile: Dockerfile
    ports:
      - "8103:8103"
    networks:
      - mynetwork
    depends_on:
      - leetcode-user-service
      - leetcode-gateway-service

  leetcode-judge-service:
    container_name: leetcode-judge-service
    build:
      context: ./leetcode-judge-service
      dockerfile: Dockerfile
    ports:
      - "8104:8104"
    networks:
      - mynetwork
    depends_on:
      - leetcode-user-service
      - leetcode-question-service
      - leetcode-gateway-service

  leetcode-sandbox-service:
    container_name: leetcode-sandbox-service
    build:
      context: ./leetcode-sandbox-service
      dockerfile: Dockerfile
    ports:
      - "8105:8105"
    networks:
      - mynetwork
    depends_on:
      - leetcode-user-service
      - leetcode-question-service
      - leetcode-judge-service
      - leetcode-gateway-service

# 网络，不定义的话就是默认网络
networks:
  mynetwork: